using Microsoft.CodeAnalysis;
using System;
using System.IO;
using System.Xml.Serialization;

namespace SmartVault.CodeGeneration
{
    [Generator]
    public class BusinessObjectSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            for (int i = 0; i < 3; i++)
            {
                var file = context.AdditionalFiles[i];
                var fileContents = file.GetText().ToString();

                var serializer = new XmlSerializer(typeof(BusinessObject));
                using var reader = new StringReader(fileContents);
                var name = Path.GetFileNameWithoutExtension(file.Path);
                var businessObjectModel = (BusinessObject)serializer.Deserialize(reader);

                string propertiesString = "";

                for (int j = 0; j < businessObjectModel.PropertyGroup.Property.Count; j++)
                {
                    var property = businessObjectModel.PropertyGroup.Property[j];
                    propertiesString += string.Format("        public {0} {1} {{ get; set; }}{2}", property.Type, property.Name, Environment.NewLine);
                }

                propertiesString += $"        public System.DateTime CreatedOn {{ get; set; }} = DateTime.UtcNow;{Environment.NewLine}";

                string businessObjectClassString = $@"// <auto-generated/>

namespace {mainMethod.ContainingNamespace.ToDisplayString()}.BusinessObjects
{{
    public partial class {name}
    {{
        {propertiesString}
    }}
}}
";

                context.AddSource($"{name}.generated.cs", businessObjectClassString);
            }
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}